### ISSUE TITLE
Add link to this repository in ignite

### ISSUE THREAD

**Issue by vfdev-5** [ryanwongsa/kaggle-birdsong-recognition#1]
Hi @ryanwongsa , congrats with the 1st place !  It was a good shake-up :) 

I'd like to add a link to this repository in ignite here : https://github.com/pytorch/ignite#others
What do you think ? 

PS: I saw you have implemented some metrics like [SedLRAPS](https://github.com/ryanwongsa/kaggle-birdsong-recognition/blob/master/src/metrics/sed_lraps.py). Would you be interested in contributing it (or them) to `ignite.contrib.metrics` ?

**Comment by ryanwongsa** [comment]
Hi @vfdev-5,

Thanks, sure sounds good to me if you add a link to the repo. 

As for the metrics, I am not too sure if they would be useful to add, as they are currently implement in a model specific way that isn't generalisable to other training methods, and might not be that useful to others.

Also thanks for quickly answering and resolving all the issues I posted in the Ignite repo over the past few months. It helped me to get everything setup and running. Ignite is an amazing library.

**Comment by vfdev-5** [comment]
Thanks @ryanwongsa for your awesome feedback ! I just added the link to your repository here : https://github.com/pytorch/ignite#others

As for the library, we are trying to build an active community and welcome everyone to contribute to it (by any kind of contributions: issues/PR/public usage etc.) So, thank you for using it in a Kaggle competition :)
Hope to see you again soon on GitHub's issues and maybe PRs for Ignite ;)
