### ISSUE TITLE
Error opening 'data/balori/XC324865.wav': System error

### ISSUE THREAD

**Issue by liuhongyan123456** [ryanwongsa/kaggle-birdsong-recognition#4]
Hello blogger, I will report an error when I put the kaggle directory data into the data directory according to your requirements.
<img width="560" alt="image" src="https://github.com/ryanwongsa/kaggle-birdsong-recognition/assets/49739798/4ac36918-820d-4955-941a-dfb06598f67b">

<img width="470" alt="image" src="https://github.com/ryanwongsa/kaggle-birdsong-recognition/assets/49739798/09745ad8-4192-4c8a-bb69-2fa994275560">
<img width="431" alt="image" src="https://github.com/ryanwongsa/kaggle-birdsong-recognition/assets/49739798/f2d19ab7-5461-46c2-be22-0a73f064e252">

**Comment by ryanwongsa** [comment]
Issue seems related the file not existing or that you have not provided the correct directory to the sound file. See issue here: https://github.com/bastibe/python-soundfile/issues/227#issue-335847436
